apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Weather App
  description: Makes API requests to get weather information for indicated locations.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Mauriceac/node-weather-website
spec:
  type: service
  lifecycle: production
  owner: guests
